import React from 'react';
import './CompanyPage.css'

function CompanyPage() {
  return (
    <>
    <div className='max-w-[1000px] w-full mx-auto flex flex-col'>
      <div className = "outer-headings text-center m-20">
            <h1 className='text-3xl'>
              Cropmind is the platform to monitor
              <div className ="inner-headings">
                <span >
                  Fertilization <br></br>
                  Irrigation <br></br>
                  Weather Data <br></br>
                  Soil Moisture <br></br>
                  Satellite Data <br></br>
                  Fertilization <br></br>
                </span>
              </div>
            </h1>
          </div>
      <div className='m-5'>
        <img src = {process.env.PUBLIC_URL + "/images/for_respected_customer.png"} alt='showing the UI of the Cropmind'></img>
      </div>
  </div>
<div className='h-40vh'>
  
</div>
<div className='max-w-[1000px] flex flex-col mx-auto'>
  

<div className="flex flex-col space-y-4 max-w-xs mx-auto">
  <input 
    placeholder="Email" 
    type="email" 
    name="email" 
    className="bg-white border-gray-300 border-2  w-full text-black px-2 py-3 min-w-[18rem] max-w-lg rounded-lg"
    style={{minHeight: '2.675rem', textIndent: '10px'}}
  />
  <button 
    type="submit" 
    className="bg-black border-purple-300 border-0  text-white font-normal w-full px-3 py-3 whitespace-nowrap rounded-lg"
    style={{minWidth: 'fit-content', minHeight: '2.675rem'}}
  >
    Join the waitlist
  </button>
</div>

 <div className='flex m-2'>
  <div className='text-center'>
    <h2 className='text-2xl'>
          <strong>Avoid being overwhelmed by data.</strong>
    </h2>
    <p className='text-xl'>
        We give you access to all of your farm's data but we make it easy
        to view all of the actions that we recommend you take such as irrigation and fertilization.
    </p>
  </div>
  

 </div>
 <div className=''>
  <img src = {process.env.PUBLIC_URL + "/images/new7days.png"} alt='showing the UI of the recommendation system'></img>
  </div>
 <div className='m-4'>
  <div className="flex justify-center items-center">
    <div className="inline-block px-4 py-1 border-solid border-gray-400 border-1 rounded-full">Features
    </div>
  </div>
 </div>
   
<h1 className='font-semibold text-2xl text-center'>
    Tools to bridge the gap between research and application.
    </h1>
 <div className='flex space-x-8'>
    <div className='w-1/2'> 
    <img className='' src = {process.env.PUBLIC_URL + "/images/undraw_undraw_flying_drone_u3r2_-3-_egfy (1).svg"} alt='a drone with a green vague background'></img>
      <h1 className='text-2xl font-bold'>
        Manage services for your drone
      </h1>
    </div>
    <div className='w-1/2'> 
    <h1 className='text-2xl font-bold'>
    <img className='' src = {process.env.PUBLIC_URL + "/images/undraw_weather_re_qsmd (1).svg"} alt='a drone with a green vague background'></img>
    Integrate weather forecasts, soil data, satellite data, seamlessly.
      </h1>
    </div>

  </div>
  <br></br>
  <div className='flex space-x-8'>
    <div className='w-1/2 size-64'> 
      <h1 className='text-2xl font-bold'>
      <img className='' src = {process.env.PUBLIC_URL + "/images/undraw_environmental_study_re_q4q8.svg"} alt='a drone with a green vague background'></img>
      Access your local institute's best irrigation practices for your crop, and have recommendations built for you.
      </h1>
    </div>
    <div className='w-1/2 '> 
    <h1 className='text-2xl font-bold'>
    <img className='' src = {process.env.PUBLIC_URL + "/images/undraw_app_installation_re_h36x.svg"} alt='a drone with a green vague background'></img>
    Access third-party applications developed with the ability to utilize the data generated by your farm to provide insights.
      </h1>
    </div>

  </div>
      
      
      <p>

        
      </p>
      </div>
 </>
 );
}

export default CompanyPage;
